"""Alembic migration environment, wired to the app's SQLModel metadata."""

from logging.config import fileConfig

from sqlalchemy import engine_from_config, pool
from sqlmodel import SQLModel

import app.models  # noqa: F401 -- registers every table on SQLModel.metadata
from alembic import context
from app.config import settings

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)

# DATABASE_URL (via app settings) is the single source of truth, so
# `alembic upgrade` always targets the same database the app connects to.
config.set_main_option("sqlalchemy.url", settings.database_url)

target_metadata = SQLModel.metadata

# SQLite cannot ALTER most column/constraint properties in place; batch mode
# makes autogenerated migrations rebuild the table instead, keeping future
# migrations runnable on the local-dev SQLite path as well as Postgres.
_render_as_batch = settings.database_url.startswith("sqlite")


def run_migrations_offline() -> None:
    """Emit migration SQL to stdout without connecting (`alembic upgrade --sql`)."""
    context.configure(
        url=settings.database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        compare_type=True,
        render_as_batch=_render_as_batch,
    )

    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            render_as_batch=_render_as_batch,
        )

        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
